on:
  push:
    branches:
      - production
name: 🚀 Deploy example.com on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: www.example.com
        username: ${{ secrets.plus_you_ftp_username }}
        password: ${{ secrets.plus_you_ftp_password }}
        server-dir: 'app_name/'

#    - name: 🔨 Migrate
#      run: python manage.py migrate
